-- Migration to extend existing tables for UX fields

ALTER TABLE rounds
  ADD COLUMN IF NOT EXISTS store VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS dropoff_point VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS notes VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS status ENUM('OPEN','LOCKED','CLOSED') NOT NULL DEFAULT 'OPEN';

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS qty INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS size VARCHAR(10) NULL,
  ADD COLUMN IF NOT EXISTS sweetness VARCHAR(10) NULL,
  ADD COLUMN IF NOT EXISTS ice VARCHAR(10) NULL,
  ADD COLUMN IF NOT EXISTS remark VARCHAR(255) NULL;
